name = "donabeya"
author = "donabe8898"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef3672735f102f62d98cb6182a805123a5e98f7d7fde368ca949283ccb5fb090"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
