name = "donabeya"
author = "donabe8898"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91d9b5500a08a81685e1fc9b845ce8c7f7b1d9d1c0222dba05a8846edafc53d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
