hash-format = "sha256"

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "afa4f499d946514c51f41f8f2202ac0946052b012570a210ebb31f0d0d627672"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/beltborne-lanterns.pw.toml"
hash = "7bc3f592bdca4665cb48ae73c20b891cb272747c64aa5f63e8a93ed1a044d1f5"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "86cf2ae835b8f3d981af2e88a4d19fdc3dc4f5aa3904c6ba30e25d77d3e9fcbb"
metafile = true

[[files]]
file = "mods/camera-mod.pw.toml"
hash = "c05be737eb2e1fc7e611694f1295f070fc7fd1088cfae396aa1d3c884fc9f38e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "22286fa216349c0767808903a0a38662857d2adee54950a18cbf26c167a06029"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "bf463928645c586cb57a4e02533ee300af3931cf9db9233dae7efc1826643d41"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
hash = "335409591f36ee18e8435cf154aff6978fcb7222a0c47a3880065733ba79bc4a"
metafile = true

[[files]]
file = "mods/create-jetpack.pw.toml"
hash = "1d8fce350ce2671f24579691c47bc178ee7b644751ecec5f068427058de0cd2b"
metafile = true

[[files]]
file = "mods/create-railways-navigator.pw.toml"
hash = "36ca424432226ba50961b9a9a9e8a9b97e3a76763c9d82ce7c5492b0822cefc0"
metafile = true

[[files]]
file = "mods/create-trainutilities.pw.toml"
hash = "70f4abe6b7351bab4fa130e15eac677e01a87ac4ab0348150590227de8343884"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "f36d13fe08a755712437ae38d4a339af7a73003152a8d3638984a11964fd83ae"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "f92e7a06645e41ea1934dc420eb2772edb1708c0d71cb427baef8cf753acb934"
metafile = true

[[files]]
file = "mods/dragonlib.pw.toml"
hash = "7f37f1846f25e9c4e9297ba1e06fe81584145f466eb5b3e45940717b0aeb3bbb"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "32078c39569bbb4b33d2d86a09cfc18a9f5b63a11d0ba2b186fd07341e422c92"
metafile = true

[[files]]
file = "mods/elytras-disabled.pw.toml"
hash = "1d0631fcb492d7f5e5172b2ef67152ca630b4605979af34e6e6f85fc80c53e41"
metafile = true

[[files]]
file = "mods/escalated.pw.toml"
hash = "e79856a2e2cee31d7d0c9476b87a7f3fa99ed05c863b3372dc12171cc2b6bdfd"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "3944c175d3409b2db40630cdc0be1cad181009cc3c20c925328cb9b04bea0108"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "5bc0953394cdd5a21d9f9c5a89dfa62ff84e43fc6a19fc5afdb7834e152386b9"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "e01a9920aa95f8bcea40bf8e56eb4fbc43b9f554375fd58d86537d3b7e19c943"
metafile = true

[[files]]
file = "mods/lightmans-currency.pw.toml"
hash = "00beec97b7f607daeaec1f8596fccfcd845a6a6d922a12275e9055eb9d69e0cf"
metafile = true

[[files]]
file = "mods/mekanism-additions.pw.toml"
hash = "2581c158a3335ec178acac32452224f0b5ae371001d99bd7757827f470abef50"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "a04147d9f39521c236191f913ac7fd8f177cc3ae073d5cb01be52bcede9acab2"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
hash = "cf382b0b1ea1f25c133779b6ea340a5953dec3272bfaef17b6b499b4e59cc515"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "2fee21be9505fb8a1a199aa5dc7a5d6a0687e86c08951fe396afd5dcfdb0ac45"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "b1e0e7bf562eb6a1eb939835c19bbc56c46d209eeba8f2b766c0ad39676a389a"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "6b100c6847b82f48ac150816c2e9ce8fd590a4dc92a49e38634b7f6c6b5a2e71"
metafile = true
