name = "donabeya"
author = "donabe8898"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "352ad79ed29f2c4b804fac8ec23ca435465f7c28e207a7027b10c532a7858f98"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
